package com.fatec.neweducation.model;
// Generated 25/08/2014 21:45:35 by Hibernate Tools 3.6.0

import com.fatec.neweducation.model.resources.TypeAnswer;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;



/**
 * Answer generated by hbm2java
 */
@Entity
@Table(name = "answer")
public class Answer implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "type_answer")
    @Enumerated(EnumType.STRING)
    private TypeAnswer typeAnswer;

    @Column(name = "response")
    private String response;

    @Column(name = "picture")
    private String picture;

    @Column(name = "audio")
    private String audio;

    @Column(name = "is_correct")
    private Boolean isCorrect;

    @OneToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "fk_question")
    private Question fkQuestion;

    public Answer() {
    }

    public Answer(TypeAnswer typeAnswer, String response, String picture, String audio, Boolean isCorrect, Question fkQuestion) {
       this.typeAnswer = typeAnswer;
       this.response = response;
       this.picture = picture;
       this.audio = audio;
       this.isCorrect = isCorrect;
       this.fkQuestion = fkQuestion;
    }

    public Answer(Integer id, TypeAnswer typeAnswer, String response, String picture, String audio, Boolean isCorrect, Question fkQuestion) {
        this.id = id;
        this.typeAnswer = typeAnswer;
        this.response = response;
        this.picture = picture;
        this.audio = audio;
        this.isCorrect = isCorrect;
        this.fkQuestion = fkQuestion;
    }

    public Answer(TypeAnswer typeAnswer, String response, String picture, String audio, Boolean isCorrect) {
        this.typeAnswer = typeAnswer;
        this.response = response;
        this.picture = picture;
        this.audio = audio;
        this.isCorrect = isCorrect;
    }

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public TypeAnswer getTypeAnswer() {
        return this.typeAnswer;
    }
    
    public void setTypeAnswer(TypeAnswer typeAnswer) {
        this.typeAnswer = typeAnswer;
    }
    public String getResponse() {
        return this.response;
    }
    
    public void setResponse(String response) {
        this.response = response;
    }
    public String getPicture() {
        return this.picture;
    }
    
    public void setPicture(String picture) {
        this.picture = picture;
    }
    public String getAudio() {
        return this.audio;
    }
    
    public void setAudio(String audio) {
        this.audio = audio;
    }
    public Boolean getIsCorrect() {
        return this.isCorrect;
    }
    
    public void setIsCorrect(Boolean isCorrect) {
        this.isCorrect = isCorrect;
    }
    public Question getFkQuestion() {
        return this.fkQuestion;
    }
    
    public void setFkQuestion(Question fkQuestion) {
        this.fkQuestion = fkQuestion;
    }




}


