package com.fatec.neweducation.model;
// Generated 25/08/2014 21:45:35 by Hibernate Tools 3.6.0


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Game generated by hbm2java
 */
@Entity
@Table(name = "game")
public class Game implements java.io.Serializable {

    private static final long serialVersionUID = 2L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "creation_date")
    @Temporal(value = TemporalType.DATE)
    private Date creationDate;

    @OneToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "fk_player_school_grade")
    private PlayerSchoolGrade fkPlayerSchoolGrade;

    @OneToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "fk_question_game")
    private Question fkQuestionGame;

    @OneToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "fk_standart")
    private Standart fkStandart;

    @Column(name = "is_correct_answer")
     private Boolean isCorrectAnswer;

    public Game() {
    }

    public Game(Date date, PlayerSchoolGrade fkPlayerSchoolGrade, Question fkQuestionGame, Boolean isCorrectAnswer) {
       this.creationDate = date;
       this.fkPlayerSchoolGrade = fkPlayerSchoolGrade;
       this.fkQuestionGame = fkQuestionGame;
       this.isCorrectAnswer = isCorrectAnswer;
    }

    public Game(Integer id, Date creationDate, PlayerSchoolGrade fkPlayerSchoolGrade, Question fkQuestionGame, Boolean isCorrectAnswer) {
        this.id = id;
        this.creationDate = creationDate;
        this.fkPlayerSchoolGrade = fkPlayerSchoolGrade;
        this.fkQuestionGame = fkQuestionGame;
        this.isCorrectAnswer = isCorrectAnswer;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    public PlayerSchoolGrade getFkPlayerSchoolGrade() {
        return this.fkPlayerSchoolGrade;
    }
    
    public void setFkPlayerSchoolGrade(PlayerSchoolGrade fkPlayerSchoolGrade) {
        this.fkPlayerSchoolGrade = fkPlayerSchoolGrade;
    }
    public Question getFkQuestionGame() {
        return this.fkQuestionGame;
    }
    
    public void setFkQuestionGame(Question fkQuestionGame) {
        this.fkQuestionGame = fkQuestionGame;
    }
    public Boolean getIsCorrectAnswer() {
        return this.isCorrectAnswer;
    }
    
    public void setIsCorrectAnswer(Boolean isCorrectAnswer) {
        this.isCorrectAnswer = isCorrectAnswer;
    }

    public Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public Standart getFkStandart() {
        return fkStandart;
    }

    public void setFkStandart(Standart fkStandart) {
        this.fkStandart = fkStandart;
    }

}


