package com.fatec.neweducation.model;
// Generated 25/08/2014 21:45:35 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;




/**
 * PlayerSchoolGrade generated by hbm2java
 */
@Entity
@Table(name = "player_school_grade")
public class PlayerSchoolGrade implements java.io.Serializable {

    private static final long serialVersionUID = 4L;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    @Column(name = "year_classe")
    private Integer yearClasse;

    @Column(name = "classe")
    private Integer classe;

    @OneToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "fk_player")
    private Player fkPlayer;

    @OneToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "fk_school")
    private School fkSchool;

    @Column(name = "active")
    private Boolean active;

    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public PlayerSchoolGrade() {
    }

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Integer getYearClasse() {
        return this.yearClasse;
    }
    
    public void setYearClasse(Integer yearClasse) {
        this.yearClasse = yearClasse;
    }
    public Integer getClasse() {
        return this.classe;
    }
    
    public void setClasse(Integer classe) {
        this.classe = classe;
    }
    public Player getFkPlayer() {
        return this.fkPlayer;
    }
    
    public void setFkPlayer(Player fkPlayer) {
        this.fkPlayer = fkPlayer;
    }
    public School getFkSchool() {
        return this.fkSchool;
    }
    
    public void setFkSchool(School fkSchool) {
        this.fkSchool = fkSchool;
    }

   


}


